routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('fronthome');
Route::POST('/update/{visit}', 'FrontController@UpdateVisit')->name('visit.update');
Route::get('/news', 'FrontController@getBerita')->name('getBerita');
Route::get('/dtlnews/{berita}', 'FrontController@dtlBerita')->name('dtlBerita');
Route::get('/client', 'FrontController@getKlien')->name('getKlien');
Route::get('/service', 'FrontController@getService')->name('getService');
Route::get('/kontak', 'FrontController@getKontak')->name('getKontak');
Route::POST('/kontak', 'FrontController@storeKontak')->name('Kontak.Store');
Route::get('/profil', 'FrontController@getProfil')->name('getProfil');
Route::get('/apply', 'FrontController@getLowongan')->name('getLowongan');
Route::get('/apply/{lowongan}', 'FrontController@getLowonganbyid')->name('getLowonganbyid');
Route::post('/apply', 'FrontController@applylowongan')->name('apply.store');
Auth::routes([
    'register' => false
]);

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('proper', 'ProPerController');
Route::resource('user', 'UserController');
Route::resource('klien', 'KlienController');
Route::resource('lowongan', 'LowonganController');
Route::resource('berita', 'BeritaController');
Route::resource('pengumuman', 'PengumumanController');
Route::resource('pelamar', 'PelamarController');
Route::resource('galeri', 'GaleriController');
Route::get('/getDownloadpelamar/{pelamar}', 'PelamarController@getDownload')->name('getDownload.pelamar');
Route::get('/getExcelpelamar', 'PelamarController@getExcel')->name('getExcel.pelamar');
Route::get('/getPdfpelamar', 'PelamarController@getPdf')->name('getPdf.pelamar');

app/Lowongan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lowongan extends Model
{
    protected $table = 'lowongan';
    protected $fillable = [
        'jabatan','status', 'deskripsi', 'dibuka','ditutup',
        'created_at','updated_at','created_by','updated_by'
    ];
    public $timestamps = true;
}

app/Http/Controllers/LowonganController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Lowongan;
use Auth;
use App\Klien;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Session;
use DB;

class LowonganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $data = DB::table('lowongan AS l')
        ->paginate(15);
        $klien = Klien::all();
        // dd($data);
        return view('admin.lowongan.lowongan',compact('data','klien'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $nama = Auth::user()->name;
        $data = Lowongan::insert([
            'perusahaan' => $request->perusahaan,
            'jabatan' => $request->jabatan,
            'deskripsi' => $request->deskripsi,
            'status' => $request->status,
            'created_by' => $nama
        ]);
        return redirect()->route('lowongan.index')->with('status','Data Berhasil Ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = DB::table('lowongan AS l')
        ->where('id_lowongan',$id)
        ->get();
        $klien = Klien::all();
        return view('admin.lowongan.edit_lowongan',compact('data','klien'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $nama = Auth::user()->name;
        $data = Lowongan::where('id_lowongan',$id)->update([
            'perusahaan' => $request->perusahaan,
             'jabatan' => $request->jabatan,
            'deskripsi' =>$request->deskripsi,
            'status' => $request->status,
            'updated_by' => $nama
        ]);
        // dd($data);
        return redirect()->route('lowongan.index')->with('alert alert-success','Data Berhasil Diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Lowongan::where('id_lowongan',$id)->delete();
        return redirect()->route('lowongan.index')->with('alert-success','Data berhasi dihapus!');
    }
    public function getLowongan()
    {
        $data = DB::table('lowongan AS l')
        ->leftjoin('klien AS k','k.id_klien','=','l.id_klien')
        ->paginate(15);
        $klien = Klien::all();
        // dd($data);
        return view('lowongan.lowongan',compact('data','klien'));
    }
    public function getLowonganbyid($id)
    {
        $data = DB::table('lowongan AS l')
        ->leftjoin('klien AS k','k.id_klien','=','l.id_klien')
        ->select('l.*','k.nama_perusahaan','k.email','k.telp')
        ->where('id_lowongan',$id)->get();
        $klien = Klien::all();
        // dd($data);
        return view('lowongan.detail',compact('data','klien'));
    }
}

resources/views/admin/lowongan/edit_lowongan.blade.php
@extends('admin.index')
@section('title')
    Lowongan
@endsection
@section('subheader')
    Halaman Admin
@endsection
@section('aktif_lowongan')
kt-menu__item--open kt-menu__item--here
@endsection
@section('content')
<div class="kt-body kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-grid--stretch" id="kt_body">
    <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">

        <div class="kt-portlet">
            <div class="kt-portlet__head">

                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
					    Edit Lowongan
					</h3>
                </div>
            </div>
            <div class="kt-form kt-form--label-right">
                <div class="kt-portlet">
                    @foreach ($data as $u)
                    <form method="post" action="{{ route('lowongan.update',$u->id_lowongan) }}"  enctype="multipart/form-data">
                      {{ csrf_field() }}
                      {{ method_field('PUT') }}
                      <div class="kt-portlet__body">
                        <div class="form-group">
                            <label for="Nama Perusahaan">Nama Perusahaan</label>
                            <input type="text" name="perusahaan" class="form-control" placeholder="perusahaan" value="{{$u->perusahaan}}">
                        </div>
                        <div class="form-group">
                            <label for="jabatan">jabatan</label>
                            <input type="text" name="jabatan" class="form-control" placeholder="jabatan" value="{{$u->jabatan}}">
                    </div>
                        <div class="form-group row">
                          <div class="col-lg-2">
                          <label for="Alamat">Deskripsi</label>
                          </div>
                          <div class="col-lg-10">
                              <textarea name="deskripsi" id="editor1" cols="100" rows="10">{{$u->deskripsi}}</textarea>
                          </div>
                        </div>
                        <div class="form-group">
                            <label for="Status">Status Lowongan</label>
                            <select class="form-control" name="status">
                                <option value="1" @if ($u->status == 1 )
                                    selected>
                                    Aktif
                                </option>
                                <option value="0">Nonaktif</option>
                                @else
                                <option value="0" selected>Nonaktif</option>
                                <option value="1">Aktif</option>
                                
                                @endif
                            </select>
                        </div>
                      <div class="kt-portlet__foot">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="{{ route('lowongan.index') }}" class=" btn btn-danger">Batal</a>
                      </div>
                    </form>
                    @endforeach
                  </div>
            </div>

        </div>
        {{--  <!--End:: Portlet-->  --}}
    </div>
    </div>
</div>
</div>
{{--  <script src="/assets/js/materialize.min.js}}"></script>  --}}
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script>
    $(document).ready(function(){

      CKEDITOR.replace('editor1', {
        height: 260,
        width: 700,
      });
    });
    </script>
@endsection

resources/views/admin/lowongan/lowongan.blade.php
@extends('admin.index')
@section('title')
    Data lowongan
@endsection

@section('aktif_lowongan')
kt-menu__item--open kt-menu__item--here
@endsection
@section('content')

@if (session('status'))
<div class="alert alert-primary fade show" role="alert">
    <div class="alert-text">{{ session('status') }}</div>
    <div class="alert-close">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"><i class="la la-close"></i></span>
        </button>
    </div>
</div>
@endif
@if(Session::has('fail'))
<div class="alert alert-danger fade show" role="alert">
    <div class="alert-text">{{Session::get('fail')}}</div>
    <div class="alert-close">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"><i class="la la-close"></i></span>
        </button>
    </div>
</div>
@endif
<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="alert alert-light alert-elevate" role="alert">
        <div class="alert-icon"><i class="flaticon-warning kt-font-brand"></i></div>
        <div class="alert-text">
            Halaman ini menampilkan data lowongan
        </div>
    </div>
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
            <div class="kt-portlet__head-label">
                <span class="kt-portlet__head-icon">
                    <i class="kt-font-brand flaticon2-line-chart"></i>
                </span>
                <h3 class="kt-portlet__head-title">
                    Data Lowongan
                </h3>
            </div>
            <div class="kt-portlet__head-toolbar">
                <div class="kt-portlet__head-wrapper">
        <div class="kt-portlet__head-actions">
            
            &nbsp;
            <button type="button" class="btn btn-primary btn-brand btn-elevate btn-icon-sm" data-toggle="modal" data-target="#tambah">
                <i class="la la-plus"></i> Tambah Data
            </button>
            {{--  <!-- Modal -->  --}}
            <div class="modal fade" id="tambah" tabindex="-1" role="dialog" aria-labelledby="tambahLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="tambahLabel">Tambah Lowongan</h5>

                  </div>
                  <form action="{{ route('lowongan.store') }}" method="POST" enctype="multipart/form-data">
                  <div class="modal-body">
                                    {{ @csrf_field() }}
                                    <div class="form-group">
                                        <label for="Nama Perusahaan">Nama Perusahaan</label>
                                        <input type="text" name="perusahaan" class="form-control" placeholder="perusahaan" value="">
                                    </div>
                                    <div class="form-group">
                                            <label for="jabatan">jabatan</label>
                                            <input type="text" name="jabatan" class="form-control" placeholder="jabatan" value="">
                                    </div>
                                    <div class="form-group row">
                                        <label for="deskripsi">deskripsi</label>
                                        <textarea cols="80" id="editor1" name="deskripsi" rows="10" data-sample-short></textarea>
                                    </div>
                                    <div class="form-group">
                                        <label for="Status">Status Lowongan</label>
                                        <select class="form-control" name="status">
                                            <option value="1">Aktif</option>
                                            <option value="0">Nonaktif</option>
                                        </select>
                                    </div>
                  </div>

                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                  </div>
                </form>
                </div>
              </div>
            </div>

        </div>
        </div>
    </div>		</div>
        </div>
        <div class="kt-portlet__body">
            <!--begin: Search Form -->
            <div class="kt-form kt-form--label-right kt-margin-t-20 kt-margin-b-10">
        <div class="row align-items-center">
            <div class="col-xl-8 order-2 order-xl-1">
                <div class="row align-items-center">
                    <div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
                        <div class="kt-input-icon kt-input-icon--left">
                            <input type="text" class="form-control" placeholder="Search..." id="generalSearch">
                            <span class="kt-input-icon__icon kt-input-icon__icon--left">
                                <span><i class="la la-search"></i></span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
            <!--end: Search Form -->
        </div>
            <div class="kt-portlet__body kt-portlet__body--fit">

                {{--  <!--begin: Datatable -->  --}}
                <table class="table  table-hover table-checkable" id="kt_table_1">
                {{-- <table class="kt-datatable" id="html_table" width="100%"> --}}
                    <thead>
                        <tr>
                            <th title="Field #1">Nama Perusahaan</th>
                            <th title="Field #2">Jabatan</th>
                            <th title="Field #3">Status Lowongan</th>
                            <th title="Field #4">Keterangan</th>
                        </tr>
                    </thead>
                    <tbody id="myTable">
                        @foreach ($data as $i)
                            <tr>
                                <td>
                                    {{ $i->perusahaan }}
                                </td>
                                <td>
                                    {{ $i->jabatan }}
                                </td>
                                <td>
                                    @if ($i->status == 1)
                                        Aktif
                                    @else
                                        Nonaktif
                                    @endif
                                </td>
                                <td><form action="{{ route('lowongan.destroy', $i->id_lowongan) }}" method="post">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    {{--  <a href="{{route('lowongan.show', $i->id_lowongan)}}" class="btn btn-sm btn-outline-info btn-icon btn-icon-sm" title="Detail"><i class="fa fa-info"></i></a>  --}}
                                    <a href="{{ route('lowongan.edit',$i->id_lowongan) }}" class="btn btn-sm btn-outline-warning btn-icon btn-icon-sm" title="Edit"><i class="fa fa-pen"></i></a>
                                    <button class="btn btn-sm btn-outline-danger btn-icon btn-icon-sm" type="submit" title="Hapus" onclick="return confirm('Yakin ingin menghapus data?')"><i class="fa fa-trash"></i></button>
                                </form></td>


                            </tr>

                        @endforeach

                    </tbody>
                </table>
                <div class="kt-datatable__pager kt-datatable--paging-loaded">
                    {{ $data->links() }}</div>
                {{--  <!--end: Datatable -->  --}}


            </div>
        </div>
    </div>
</div>

{{--  <!-- end:: Content -->  --}}
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script>
    $(document).ready(function(){
      $("#generalSearch").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#myTable tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
      CKEDITOR.replace('editor1', {
        height: 260,
        width: 450,
      });

      jQuery.fn.filterByText = function(textbox) {
        return this.each(function() {
          var select = this;
          var options = [];
          $(select).find('option').each(function() {
            options.push({
              value: $(this).val(),
              text: $(this).text()
            });
          });
          $(select).data('options', options);
      
          $(textbox).bind('change keyup', function() {
            var options = $(select).empty().data('options');
            var search = $.trim($(this).val());
            var regex = new RegExp(search, "gi");
      
            $.each(options, function(i) {
              var option = options[i];
              if (option.text.match(regex) !== null) {
                $(select).append(
                  $('<option>').text(option.text).val(option.value)
                );
              }
            });
          });
        });
      };
      
      // You could use it like this:
      
      $(function() {
        $('select').filterByText($('input'));
      });
 
    });
    </script>
    <script>
    </script>
@endsection