routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('fronthome');
Route::POST('/update/{visit}', 'FrontController@UpdateVisit')->name('visit.update');
Route::get('/news', 'FrontController@getBerita')->name('getBerita');
Route::get('/dtlnews/{berita}', 'FrontController@dtlBerita')->name('dtlBerita');
Route::get('/client', 'FrontController@getKlien')->name('getKlien');
Route::get('/service', 'FrontController@getService')->name('getService');
Route::get('/kontak', 'FrontController@getKontak')->name('getKontak');
Route::POST('/kontak', 'FrontController@storeKontak')->name('Kontak.Store');
Route::get('/profil', 'FrontController@getProfil')->name('getProfil');
Route::get('/apply', 'FrontController@getLowongan')->name('getLowongan');
Route::get('/apply/{lowongan}', 'FrontController@getLowonganbyid')->name('getLowonganbyid');
Route::post('/apply', 'FrontController@applylowongan')->name('apply.store');
Auth::routes([
    'register' => false
]);

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('proper', 'ProPerController');
Route::resource('user', 'UserController');
Route::resource('klien', 'KlienController');
Route::resource('lowongan', 'LowonganController');
Route::resource('berita', 'BeritaController');
Route::resource('pengumuman', 'PengumumanController');
Route::resource('pelamar', 'PelamarController');
Route::resource('galeri', 'GaleriController');
Route::get('/getDownloadpelamar/{pelamar}', 'PelamarController@getDownload')->name('getDownload.pelamar');
Route::get('/getExcelpelamar', 'PelamarController@getExcel')->name('getExcel.pelamar');
Route::get('/getPdfpelamar', 'PelamarController@getPdf')->name('getPdf.pelamar');

app/Klien.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Klien extends Model
{
    protected $table = 'klien';
    protected $fillable = [
        'nama_perusahaan','deskripsi', 'logo', 'website','email','telp','alamat',
        'created_at','updated_at','created_by','updated_by'
    ];
    public $timestamps = true;
}

app/Http/Controllers/KlienController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Klien;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Session;

use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Auth;
class KlienController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $data = Klien::paginate(15);
        // dd($data);
        return view('admin.klien.klien',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'nama_perusahaan' => 'required',
            'deskripsi' => 'required',
        ]);

        if ($validator->fails()) {
            return redirect()->route('klien.index')
                        ->withFail('Error Message');
        }
        $nama = Auth::user()->name;
        $file = $request->file('logo');
        if ($file!='') {
            $file = $request->file('logo');
            $extension=$file->getClientOriginalExtension();
            $destinationPath = 'assets/images/klien';
            $fileName = rand(11111, 99999) . '.' . $extension;
            $request->file('logo')->move($destinationPath, $fileName);
            $data = Klien::insert([
                'logo' => $fileName,
                'nama_perusahaan' => $request->nama_perusahaan,
                'deskripsi' => $request->deskripsi,
                'website' => $request->website,
                'alamat' => $request->alamat,
                'email' => $request->email,
                'telp' => $request->telp,
                'created_by' => $nama
            ]);
        }else{
            $data = Klien::insert([

                'nama_perusahaan' => $request->nama_perusahaan,
                'deskripsi' => $request->deskripsi,
                'website' => $request->website,
                'alamat' => $request->alamat,
                'email' => $request->email,
                'telp' => $request->telp,
                'created_by' => $nama
            ]);
        }
        return redirect()->route('klien.index')->with('status','Data Berhasil Ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Klien::where('id_klien',$id)->get();
        // dd($data);
        return view('admin.klien.edit_klien',compact('data'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $nama = Auth::user()->name;
        $file = $request->file('gambar');
        if ($file!='') {
            $file = $request->file('gambar');
            $extension=$file->getClientOriginalExtension();
            $destinationPath = 'assets/images/klien';
            $fileName = rand(11111, 99999) . '.' . $extension;
            $request->file('gambar')->move($destinationPath, $fileName);
            $data = Klien::where('id_klien',$id)
                ->update([
                    'logo' => $fileName,
                    'nama_perusahaan' => $request->nama_perusahaan,
                    'deskripsi' => $request->deskripsi,
                    'website' => $request->website,
                    'email' => $request->email,
                    'alamat' => $request->alamat,
                    'telp' => $request->telp,
                    'updated_by' => $nama
                ]);
        }else{
            $data = Klien::where('id_klien',$id)
                ->update([
                    'nama_perusahaan' => $request->nama_perusahaan,
                    'deskripsi' => $request->deskripsi,
                    'website' => $request->website,
                    'email' => $request->email,
                    'alamat' => $request->alamat,
                    'telp' => $request->telp,
                    'updated_by' => $nama
                ]);
        }


    return redirect()->route('klien.index')->with('alert-success','Data Berhasil Diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Klien::where('id_klien',$id)->delete();
        return redirect()->route('klien.index')->with('alert-success','Data berhasi dihapus!');
    }
}

resources/views/admin/klien/edit_klien.blade.php
@extends('admin.index')
@section('title')
    Profil
@endsection
@section('subheader')
    Halaman Admin
@endsection
@section('aktif_klien')
kt-menu__item--open kt-menu__item--here
@endsection
@section('content')
<div class="kt-body kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-grid--stretch" id="kt_body">
    <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">

        <div class="kt-portlet">
            <div class="kt-portlet__head">

                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
					    Edit Klien
					</h3>
                </div>
            </div>
            <div class="kt-form kt-form--label-right">
                <div class="kt-portlet">
                    @foreach ($data as $u)
                    <form method="post" action="{{ route('klien.update',$u->id_klien) }}"  enctype="multipart/form-data">
                      {{ csrf_field() }}
                      {{ method_field('PUT') }}
                      <div class="kt-portlet__body">
                        <div class="form-group row">
                            <label class="col-xl-3 col-lg-3 col-form-label">Logo </label>
                            <div class="col-lg-9 col-xl-6">
                                <img class="kt-avatar__holder" src="/assets/images/klien/{{$u->logo}}" id="showgambar" style="height:300px;" alt="">
                                <input type="file" id="inputgambar" name="gambar" value="{{$u->logo}}" class="validate"/ >
                            </div>
                        </div>
                        <div class="form-group">
                          <label for="Nama">Nama Perusahaan</label>
                          <input type="text" name="nama_perusahaan" class="form-control" placeholder="Nama Perusahaan" value="{{$u->nama_perusahaan}}">
                        </div>
                        <div class="form-group row">
                          <div class="col-lg-2">
                          <label for="Alamat">Deskripsi</label>
                          </div>
                          <div class="col-lg-10">
                              <textarea name="deskripsi"  cols="100" rows="10">{{$u->deskripsi}}</textarea>
                          </div>
                        </div>
                        <div class="form-group">
                            <label for="Website">Website</label>
                            <input type="text" name="website" class="form-control" placeholder="Website" value="{{$u->website}}">
                          </div>
                          <div class="form-group">
                            <label for="Email">Email</label>
                            <input type="email" name="email" class="form-control" placeholder="Email" value="{{$u->email}}">
                          </div>
                          <div class="form-group row">
                            <div class="col-lg-2">
                            <label for="Alamat">Alamat</label>
                            </div>
                            <div class="col-lg-10">
                                <textarea name="alamat"  cols="100" rows="10">{{$u->alamat}}</textarea>
                            </div>
                          </div>
                          <div class="form-group">
                            <label for="Telephone">Telephone</label>
                            <input type="text" name="telp" class="form-control" placeholder="No. Telphone" value="{{$u->telp}}">
                          </div>
                      <div class="kt-portlet__foot">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="{{ route('klien.index') }}" class=" btn btn-danger">Batal</a>
                      </div>
                    </form>
                    @endforeach
                  </div>
            </div>

        </div>
        {{--  <!--End:: Portlet-->  --}}
    </div>
    </div>
</div>
</div>
{{--  <script src="/assets/js/materialize.min.js}}"></script>  --}}
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript">

    function readURL(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();

          reader.onload = function (e) {
              $('#showgambar').attr('src', e.target.result);
          }

          reader.readAsDataURL(input.files[0]);
      }
  }

  $("#inputgambar").change(function () {
      readURL(this);
  });

</script>

@endsection

resources/views/admin/klien/klien.blade.php
@extends('admin.index')
@section('title')
    Data klien
@endsection

@section('aktif_klien')
kt-menu__item--open kt-menu__item--here
@endsection
@section('content')
@if (session('status'))
<div class="alert alert-primary fade show" role="alert">
    <div class="alert-text">{{ session('status') }}</div>
    <div class="alert-close">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"><i class="la la-close"></i></span>
        </button>
    </div>
</div>
@endif
@if(Session::has('fail'))
<div class="alert alert-danger fade show" role="alert">
    <div class="alert-text">{{Session::get('fail')}}</div>
    <div class="alert-close">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"><i class="la la-close"></i></span>
        </button>
    </div>
</div>
@endif
<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="alert alert-light alert-elevate" role="alert">
        <div class="alert-icon"><i class="flaticon-warning kt-font-brand"></i></div>
        <div class="alert-text">
            Halaman ini menampilkan data klien
        </div>
    </div>
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
            <div class="kt-portlet__head-label">
                <span class="kt-portlet__head-icon">
                    <i class="kt-font-brand flaticon2-line-chart"></i>
                </span>
                <h3 class="kt-portlet__head-title">
                    Data klien
                </h3>
            </div>
            <div class="kt-portlet__head-toolbar">
                <div class="kt-portlet__head-wrapper">
        <div class="kt-portlet__head-actions">

            &nbsp;
            <button type="button" class="btn btn-primary btn-brand btn-elevate btn-icon-sm" data-toggle="modal" data-target="#tambah">
                <i class="la la-plus"></i> Tambah Data
            </button>
            <!-- Modal -->
            <div class="modal fade" id="tambah" tabindex="-1" role="dialog" aria-labelledby="tambahLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="tambahLabel">Tambah Klien</h5>

                  </div>
                  <form action="{{ route('klien.store') }}" method="POST" enctype="multipart/form-data">
                  <div class="modal-body">
                                    {{ @csrf_field() }}
                                    <div class="form-group">
                                            <label for="nama_perusahaan">nama_perusahaan</label>
                                            <input type="text" name="nama_perusahaan" class="form-control" placeholder="nama perusahaan" value="">
                                    </div>
                                    <div class="form-group">
                                            <label for="logo">Logo</label>
                                            <input type="file" name="logo" class="form-control" placeholder="logo" value="">
                                    </div>
                                    <div class="form-group">
                                            <label for="website">website</label>
                                            <input type="text" name="website" class="form-control" placeholder="website" value="">
                                    </div>
                                    <div class="form-group">
                                            <label for="email">email</label>
                                            <input type="email" name="email" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="telp">telp</label>
                                        <input type="text" name="telp" class="form-control">
                                </div>
                                <div class="form-group row">
                                    <label for="alamat">alamat</label>
                                    <textarea name="alamat" id="" cols="70" rows="7"></textarea>
                            </div>
                            <div class="form-group row">
                                <label for="deskripsi">deskripsi</label>
                                <textarea name="deskripsi" id="" cols="70" rows="7"></textarea>
                        </div>
                  </div>

                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                  </div>
                </form>
                </div>
              </div>
            </div>

        </div>
    </div>		</div>
        </div>
        <div class="kt-portlet__body">
            <!--begin: Search Form -->
            <div class="kt-form kt-form--label-right kt-margin-t-20 kt-margin-b-10">
        <div class="row align-items-center">
            <div class="col-xl-8 order-2 order-xl-1">
                <div class="row align-items-center">
                    <div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
                        <div class="kt-input-icon kt-input-icon--left">
                            <input type="text" class="form-control" placeholder="Search..." id="generalSearch">
                            <span class="kt-input-icon__icon kt-input-icon__icon--left">
                                <span><i class="la la-search"></i></span>
                            </span>
                        </div>
                    </div>


                </div>
            </div>

        </div>
    </div>
            <!--end: Search Form -->
        </div>
            <div class="kt-portlet__body kt-portlet__body--fit">

                {{--  <!--begin: Datatable -->  --}}
                <table class="table  table-hover table-checkable" id="kt_table_1">
                {{-- <table class="kt-datatable" id="html_table" width="100%"> --}}
                    <thead>
                        <tr>
                            <th title="Field #1">Logo</th>
                            <th title="Field #2">Nama Perusahaan</th>
                            <th title="Field #3">website</th>
                            <th title="Field #4">Keterangan</th>
                        </tr>
                    </thead>
                    <tbody id="myTable">
                        @foreach ($data as $i)
                            <tr>
                                <td class="kt-datatable__cell">
                                <img src="{{url('assets/images/klien/'. $i->logo)}}" width="100px" alt="image" style="margin-right: 10px;" />

                            </td>
                                <td class="kt-datatable__cell">
                                    {{ $i->nama_perusahaan }}
                                </td>
                                <td class="kt-datatable__cell">
                                    {{ $i->website }}
                                </td>
                                <td class="kt-datatable__cell"><form action="{{ route('klien.destroy', $i->id_klien) }}" method="post">
                                    {{ csrf_field() }}
                                   {{ method_field('DELETE') }}
                                    {{--  <a href="{{route('klien.show', $i->id_klien)}}" class="btn btn-sm btn-outline-info btn-icon btn-icon-sm" title="Detail"><i class="fa fa-info"></i></a>  --}}
                                    <a href="{{ route('klien.edit',$i->id_klien) }}" class="btn btn-sm btn-outline-warning btn-icon btn-icon-sm" title="Edit"><i class="fa fa-pen"></i></a>
                                    <button class="btn btn-sm btn-outline-danger btn-icon btn-icon-sm" type="submit" title="Hapus" onclick="return confirm('Yakin ingin menghapus data?')"><i class="fa fa-trash"></i></button>
                                </form></td>
                            </tr>

                        @endforeach

                    </tbody>
                </table>
                <div class="kt-datatable__pager kt-datatable--paging-loaded">
                    {{ $data->links() }}</div>
                {{--  <!--end: Datatable -->  --}}


            </div>
        </div>
    </div>
</div>

{{--  <!-- end:: Content -->  --}}
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
      $("#generalSearch").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#myTable tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
    </script>

@endsection