routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('fronthome');
Route::POST('/update/{visit}', 'FrontController@UpdateVisit')->name('visit.update');
Route::get('/news', 'FrontController@getBerita')->name('getBerita');
Route::get('/dtlnews/{berita}', 'FrontController@dtlBerita')->name('dtlBerita');
Route::get('/client', 'FrontController@getKlien')->name('getKlien');
Route::get('/service', 'FrontController@getService')->name('getService');
Route::get('/kontak', 'FrontController@getKontak')->name('getKontak');
Route::POST('/kontak', 'FrontController@storeKontak')->name('Kontak.Store');
Route::get('/profil', 'FrontController@getProfil')->name('getProfil');
Route::get('/apply', 'FrontController@getLowongan')->name('getLowongan');
Route::get('/apply/{lowongan}', 'FrontController@getLowonganbyid')->name('getLowonganbyid');
Route::post('/apply', 'FrontController@applylowongan')->name('apply.store');
Auth::routes([
    'register' => false
]);

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('proper', 'ProPerController');
Route::resource('user', 'UserController');
Route::resource('klien', 'KlienController');
Route::resource('lowongan', 'LowonganController');
Route::resource('berita', 'BeritaController');
Route::resource('pengumuman', 'PengumumanController');
Route::resource('pelamar', 'PelamarController');
Route::resource('galeri', 'GaleriController');
Route::get('/getDownloadpelamar/{pelamar}', 'PelamarController@getDownload')->name('getDownload.pelamar');
Route::get('/getExcelpelamar', 'PelamarController@getExcel')->name('getExcel.pelamar');
Route::get('/getPdfpelamar', 'PelamarController@getPdf')->name('getPdf.pelamar');

app/Berita.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Berita extends Model
{
    protected $table = 'berita';
    protected $dates = ['created_at', 'updated_at'];
    protected $fillable = [
        'foto','judul','subjudul','isi','status',
        'created_at','updated_at','created_by','updated_by'
    ];
    public $timestamps = true;
}

app/Http/Controllers/BeritaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Berita;
use Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Session;

class BeritaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $data = Berita::paginate(15);
        return view('admin.berita.berita', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'isi' => 'required',
            'judul' => 'required',
        ]);

        if ($validator->fails()) {
            return redirect()->route('berita.index')
                        ->withFail('Error Message');
        }
        $nama = Auth::user()->name;
        $file = $request->file('foto');
        if ($file !='') {
            $file = $request->file('foto');
            $extension=$file->getClientOriginalExtension();
            $destinationPath = 'assets/images/berita';
            $fileName = rand(11111, 99999) . '.' . $extension;
            $request->file('foto')->move($destinationPath, $fileName);
            $data = Berita::insert([
                'foto' => $fileName,
                'judul' => $request->judul,
                'subjudul' => $request->subjudul,
                'isi' => $request->isi,
                'status' => $request->status,
                'created_by' => $nama,
            ]);
        }else{
            $data = Berita::insert([

                'judul' => $request->judul,
                'subjudul' => $request->subjudul,
                'isi' => $request->isi,
                'status' => $request->status,
                'created_by' => $nama,
            ]);
        }
        return redirect()->route('berita.index')->with('status','Data Berhasil Ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Berita::where('id_berita',$id)->get();
        return view('admin.berita.edit_berita',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $nama = Auth::user()->name;
        $file = $request->file('gambar');
        if ($file!='') {
            $file = $request->file('gambar');
            $extension=$file->getClientOriginalExtension();
            $destinationPath = 'assets/images/pengumuman';
            $fileName = rand(11111, 99999) . '.' . $extension;
            $request->file('gambar')->move($destinationPath, $fileName);
            $data = Berita::where('id_berita',$id)
                ->update([
                    'foto' => $fileName,
                    'judul' => $request->judul,
                    'subjudul' => $request->subjudul,
                    'status' => $request->status,
                    'updated_by' => $nama
                ]);
        }else{
            $data = Berita::where('id_berita',$id)
                ->update([
                    'judul' => $request->judul,
                    'subjudul' => $request->subjudul,
                    'status' => $request->status,
                    'updated_by' => $nama
                ]);
        }


    return redirect()->route('berita.index')->with('status','Data Berhasil Diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Berita::where('id_berita',$id)->delete();
        return redirect()->route('berita.index')->with('status','Data Berhasil dihapus');

    }
}

resources/views/admin/berita/berita.blade.php
@extends('admin.index')
@section('title')
    Data berita
@endsection

@section('aktif_berita')
kt-menu__item--open kt-menu__item--here
@endsection
@section('content')
@if (session('status'))
<div class="alert alert-primary fade show" role="alert">
    <div class="alert-text">{{ session('status') }}</div>
    <div class="alert-close">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"><i class="la la-close"></i></span>
        </button>
    </div>
</div>
@endif
@if(Session::has('fail'))
<div class="alert alert-danger fade show" role="alert">
    <div class="alert-text">{{Session::get('fail')}}</div>
    <div class="alert-close">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"><i class="la la-close"></i></span>
        </button>
    </div>
</div>
@endif

<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="alert alert-light alert-elevate" role="alert">
        <div class="alert-icon"><i class="flaticon-warning kt-font-brand"></i></div>
        <div class="alert-text">
            Halaman ini menampilkan data Berita
        </div>
    </div>
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
            <div class="kt-portlet__head-label">
                <span class="kt-portlet__head-icon">
                    <i class="kt-font-brand flaticon2-line-chart"></i>
                </span>
                <h3 class="kt-portlet__head-title">
                    Data Berita
                </h3>
            </div>
            <div class="kt-portlet__head-toolbar">
                <div class="kt-portlet__head-wrapper">
        <div class="kt-portlet__head-actions">

            &nbsp;
            <button type="button" class="btn btn-primary btn-brand btn-elevate btn-icon-sm" data-toggle="modal" data-target="#tambah">
                <i class="la la-plus"></i> Tambah Data
            </button>
            <!-- Modal -->
            <div class="modal fade" id="tambah" tabindex="-1" role="dialog" aria-labelledby="tambahLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="tambahLabel">Tambah Klien</h5>

                  </div>
                  <form action="{{ route('berita.store') }}" name="berita" method="POST" enctype="multipart/form-data">
                  <div class="modal-body">
                    <style>
                         .error {
                             color:red;
                         }
                     </style>
                                    {{ @csrf_field() }}
                                    <div class="form-group">
                                            <label for="judul">judul</label>
                                            <input type="text" name="judul" class="form-control" placeholder="judul" >
                                    </div>
                                    <div class="form-group">
                                            <label for="subjudul">subjudul</label>
                                            <input type="text" name="subjudul" class="form-control" placeholder="subjudul" >
                                    </div>
                                    <div class="form-group">
                                            <label for="logo">Foto</label>
                                            <input type="file" name="foto" class="form-control" placeholder="foto" >
                                    </div>
                            <div class="form-group row">
                                <label for="isi">isi</label>
                                <textarea id="editor1" name="isi" id="" cols="70" rows="7"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="Status">Status Berita</label>
                            <select class="form-control" name="status">
                                <option value="1">Aktif</option>
                                <option value="0">Nonaktif</option>
                            </select>
                        </div>
                  </div>

                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                  </div>
                </form>
                </div>
              </div>
            </div>


        </div>
    </div>		</div>
        </div>
        <div class="kt-portlet__body">
            {{--  <!--begin: Search Form -->  --}}
            <div class="kt-form kt-form--label-right kt-margin-t-20 kt-margin-b-10">
        <div class="row align-items-center">
            <div class="col-xl-8 order-2 order-xl-1">
                <div class="row align-items-center">
                    <div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
                        <div class="kt-input-icon kt-input-icon--left">
                            <input type="text" class="form-control" placeholder="Search..." id="generalSearch">
                            <span class="kt-input-icon__icon kt-input-icon__icon--left">
                                <span><i class="la la-search"></i></span>
                            </span>
                        </div>
                    </div>


                </div>
            </div>

        </div>
    </div>
            <!--end: Search Form -->
        </div>
            <div class="kt-portlet__body kt-portlet__body--fit">

                {{--  <!--begin: Datatable -->  --}}
                <table class="table  table-hover table-checkable" id="kt_table_1">
                {{-- <table class="kt-datatable" id="html_table" width="100%"> --}}
                    <thead>
                        <tr>
                            <th title="Field #1">Foto</th>
                            <th title="Field #1">Judul</th>
                            <th title="Field #1">Subjudul</th>
                            <th title="Field #3">Status Berita</th>
                            <th title="Field #5">Keterangan</th>

                        </tr>
                    </thead>
                    <tbody id="myTable">
                        @foreach ($data as $i)
                            <tr>
                                <td>
                                    <img src="{{url('assets/images/berita/'. $i->foto)}}" width="100px" alt="image" style="margin-right: 10px;" />
                                </td>
                                <td>
                                    {{ $i->judul }}
                                </td>
                                <td>
                                    {{ $i->subjudul }}
                                </td>
                                <td>
                                    @if ($i->status == 1)
                                        Aktif
                                    @else
                                        Nonaktif
                                    @endif
                                </td>
                                <td><form action="{{ route('berita.destroy', $i->id_berita) }}" method="post">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    {{--  <a href="{{route('berita.show', $i->id_berita)}}" class="btn btn-sm btn-outline-info btn-icon btn-icon-sm" title="Detail"><i class="fa fa-info"></i></a>  --}}
                                    <a href="{{ route('berita.edit',$i->id_berita) }}" class="btn btn-sm btn-outline-warning btn-icon btn-icon-sm" title="Edit"><i class="fa fa-pen"></i></a>
                                    <button class="btn btn-sm btn-outline-danger btn-icon btn-icon-sm" type="submit" title="Hapus" onclick="return confirm('Yakin ingin menghapus data?')"><i class="fa fa-trash"></i></button>
                                </form></td>


                            </tr>

                        @endforeach

                    </tbody>
                </table>
                <div class="kt-datatable__pager kt-datatable--paging-loaded">
                    {{ $data->links() }}</div>
                {{--  <!--end: Datatable -->  --}}


            </div>
        </div>
    </div>
</div>

{{--  <!-- end:: Content -->  --}}
</div>

<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="
https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/jquery.validate.min.js"></script>
<script>
    $(document).ready(function(){
      $("#generalSearch").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#myTable tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
      CKEDITOR.replace('editor1', {
        height: 260,
        width: 450,
      });

    });
    </script>
   <script type="text/javascript">
    $(function() {
        // Initialize form validation on the registration form.
        // It has the name attribute "registration"
        $("form[name='berita']").validate({
          // Specify validation rules
          rules: {
            // The key name on the left side is the name attribute
            // of an input field. Validation rules are defined
            // on the right side
            judul: "required",
            subjudul: "required",
            foto:{
                required :true,
                extension: "jpg,jpeg,png",
                filesize:2000
            },
            isi: "required",
            status: "required",
          },
          // Specify validation error messages
          messages: {
            judul: "Masukan Judul",
            subjudul: "masukan subjudul",
            foto: {
              required: "masukan gambar",
              extension: "file hanya boleh format jpg,jpeg, dan png",
              filesize: "ukuran file maksimum 2 MB"
            },
            isi: "Masukan isi konten",
            status: "Pilih status"
          },
          // Make sure the form is submitted to the destination defined
          // in the "action" attribute of the form when valid
          submitHandler: function(form) {
            form.submit();
          }
        });
      });
</script>
@endsection

resources/views/admin/berita/edit_berita.blade.php
@extends('admin.index')
@section('title')
    Berita
@endsection
@section('subheader')
    Halaman Admin
@endsection
@section('aktif_berita')
kt-menu__item--open kt-menu__item--here
@endsection
@section('content')
<div class="kt-body kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-grid--stretch" id="kt_body">
    <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">

        <div class="kt-portlet">
            <div class="kt-portlet__head">

                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
					    Edit Berita
					</h3>
                </div>
            </div>
            <div class="kt-form kt-form--label-right">
                <div class="kt-portlet">
                    @foreach ($data as $u)
                    <form method="post" action="{{ route('berita.update',$u->id_berita) }}"  enctype="multipart/form-data">
                      {{ csrf_field() }}
                      {{ method_field('PUT') }}
                      <div class="kt-portlet__body">
                        <div class="form-group row">
                            <label class="col-xl-3 col-lg-3 col-form-label">Foto </label>
                            <div class="col-lg-9 col-xl-6">
                                <img class="kt-avatar__holder" src="/assets/images/berita/{{$u->foto}}" id="showgambar" style="height:300px;" alt="">
                                <input type="file" id="inputgambar" name="gambar" value="{{$u->foto}}" class="validate"/ >
                            </div>
                        </div>     <div class="form-group">
                            <label for="judul">judul</label>
                            <input type="text" name="judul" class="form-control" placeholder="judul" value="{{$u->judul}}">
                    </div>
                    <div class="form-group">
                            <label for="subjudul">subjudul</label>
                            <input type="text" name="subjudul" class="form-control" placeholder="subjudul" value="{{$u->subjudul}}">
                    </div>
                    <div class="form-group">
                        <label for="isi">isi</label>
                        <textarea id="editor1" name="isi" id="" cols="70" rows="7">{{ $u->isi }}</textarea>
                </div>
                <div class="form-group">
                    <label for="Status">Status Berita</label>
                    <select class="form-control" name="status">
                        <option value="1" @if ($u->status == 1 )
                            selected>
                            Aktif
                        </option>
                        <option value="0">Nonaktif</option>
                        @else
                        <option value="0" selected>Nonaktif</option>
                        <option value="1">Aktif</option>
                        
                        @endif
                    </select>
                </div>
                      <div class="kt-portlet__foot">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="{{ route('berita.index') }}" class=" btn btn-danger">Batal</a>
                      </div>
                    </form>
                    @endforeach
                  </div>
            </div>

        </div>
        {{--  <!--End:: Portlet-->  --}}
    </div>
    </div>
</div>
</div>
{{--  <script src="/assets/js/materialize.min.js}}"></script>  --}}
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript">

    function readURL(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();

          reader.onload = function (e) {
              $('#showgambar').attr('src', e.target.result);
          }

          reader.readAsDataURL(input.files[0]);
      }
  }

  $("#inputgambar").change(function () {
      readURL(this);
  });


</script>
<script>
    $(document).ready(function(){
        CKEDITOR.replace('editor1', {
            height: 260,
            width: 900,
          });
    });
</script>
@endsection